# Generated by Django 5.0.3 on 2024-03-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
