# Generated by Django 5.0.3 on 2024-03-20 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', max_length=8)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_requests', to='meetup.meetingrequest')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.place')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('08:00', '08:00 - 08:30'), ('08:30', '08:30 - 09:00'), ('09:00', '09:00 - 09:30'), ('09:30', '09:30 - 10:00'), ('10:00', '10:00 - 10:30'), ('10:30', '10:30 - 11:00'), ('11:00', '11:00 - 11:30'), ('11:30', '11:30 - 12:00'), ('12:00', '12:00 - 12:30'), ('12:30', '12:30 - 13:00'), ('13:00', '13:00 - 13:30'), ('13:30', '13:30 - 14:00'), ('14:00', '14:00 - 14:30'), ('14:30', '14:30 - 15:00'), ('15:00', '15:00 - 15:30'), ('15:30', '15:30 - 16:00'), ('16:00', '16:00 - 16:30'), ('16:30', '16:30 - 17:00'), ('17:00', '17:00 - 17:30'), ('17:30', '17:30 - 18:00'), ('18:00', '18:00 - 18:30')], max_length=5)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='meetup.meetingrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
