# Generated by Django 5.0.3 on 2024-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_place_meetingrequest_placerequest_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='request_from_accepting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='request_to_accepting',
            field=models.BooleanField(default=False),
        ),
    ]
