# Generated by Django 5.0.3 on 2024-03-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_meetingrequest_request_from_accepting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='meeting_request',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='requested_by',
        ),
        migrations.CreateModel(
            name='PlaceTimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_time_requests', to='meetup.meetingrequest')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.place')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.timeslot')),
            ],
        ),
        migrations.DeleteModel(
            name='PlaceRequest',
        ),
    ]
