# Generated by Django 5.0.3 on 2024-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_code_sent_at_user_verification_code_and_more'),
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='meetup.interest'),
        ),
    ]
