# Generated by Django 5.0.3 on 2024-03-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_userinfo_interests'),
        ('meetup', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='meetup.interest'),
        ),
    ]
