# Generated by Django 5.0.3 on 2024-03-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userinfo_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='users',
            new_name='interests',
        ),
    ]
