# Generated by Django 5.0.3 on 2024-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userinfo_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='loc_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='loc_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
