# Generated by Django 5.1.1 on 2024-09-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userinfo_loc_lat_userinfo_loc_lon'),
        ('meetup', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='meetup.city'),
        ),
    ]
