# Generated by Django 5.1.1 on 2024-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_url',
            field=models.URLField(default='https://www.test.com'),
            preserve_default=False,
        ),
    ]
